name = "MyTestModia"
uuid = "7302d7c8-0804-4ec0-9bce-7b215e2849e8"
authors = ["VincentL"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
